# Generated by Django 2.2.6 on 2019-10-13 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20191013_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Sale', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='housetype',
            field=models.CharField(default='Residential', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='living',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(default='House', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 10, 37, 54, 775010)),
        ),
    ]
