# Generated by Django 2.2.6 on 2019-10-13 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20191013_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='housetype',
        ),
        migrations.AddField(
            model_name='listing',
            name='propertytype',
            field=models.CharField(blank=True, default='Residential', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 11, 22, 30, 95569)),
        ),
    ]
