# Generated by Django 2.2.6 on 2019-10-13 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('is_mvp', models.BooleanField(default=True)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 8, 50, 16, 305339))),
            ],
        ),
    ]
