# Generated by Django 2.2.6 on 2019-10-13 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20191013_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 10, 17, 20, 721352)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
